name: recipe_api_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  http: ^1.5.0
  translator: ^1.0.0
  cached_network_image: ^3.2.3
  shared_preferences: ^2.2.0
  cupertino_icons: ^1.0.2
  provider: ^6.1.5
  flutter_staggered_animations: ^1.1.1
  url_launcher: ^6.1.14
  shimmer: ^2.0.0
  lottie: ^2.7.0
  iconsax: ^0.0.8
  package_info_plus: ^8.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
